"""
Django settings for filebrowser_sample project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@pomxx+s+fk(js-*n4rqzzlh-y43&ct*q#%g^e3%p%17l51=sq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'filebrowser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'blog',
    'filebrowser_sample',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'filebrowser_sample.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'filebrowser_sample.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



####################
# TINYMCE SETTINGS #
####################
TINYMCE_DEFAULT_CONFIG = {
    'plugins': 'table,paste,spellchecker,searchreplace,'
                'image,media,link,anchor,code,fullscreen,lists,'
                'contextmenu,hr,paste,searchreplace,textcolor',
    'toolbar1': 'undo redo | styleselect | forecolor backcolor bold italic | '
                'alignleft aligncenter alignright alignjustify | '
                'bullist numlist outdent indent | link unlink image | code spellchecker',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'spellchecker_language': 'de_DE',
    'browser_spellcheck' : True,
    'width': 'auto',
    'height': 400,
    'image_advtab': True,
    'branding': False,
    'image_class_list': [
        {'title': 'None', 'value': ''},
        {'title': 'Variable Größe', 'value': 'img-fluid'},
        {'title': 'Runde Ecken', 'value': 'rounded'}
    ],
    'link_class_list': [
        {'title': 'None', 'value': ''},
        {'title': 'Bild vergrösserbar', 'value': 'blogthumb'}
    ],
    'menu': {
        'edit': {'title': 'Edit', 'items': 'undo redo | cut copy paste pastetext | selectall | searchreplace'},
        'insert': {'title': 'Insert', 'items': 'image link media anchor | hr'},
        'view': {'title': 'View', 'items': 'code fullscreen'},
        'format': {'title': 'Format', 'items': 'bold italic underline strikethrough superscript subscript | removeformat'},
        'table': {'title': 'Table', 'items': 'inserttable tableprops deletetable | cell row column'},
        'tools': {'title': 'Tools', 'items': 'spellchecker'}
    },
}
TINYMCE_SPELLCHECKER = False
TINYMCE_COMPRESSOR = True