# Generated by Django 3.1.1 on 2020-11-29 16:03

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
            },
        ),
    ]
